version: "{branch}.{build}"

configuration: "Release"

platform: "x64"

branches:
  only:
    - master
	- release

os: "Visual Studio 2017"

shallow_copy: "true"
clone_depth: "1"

notifications:
  - provider: "Webhooks"
    url: "gitter appveyor integration link"
	on_build_success: "true"
	on_build_failure: "true"
	on_build_status_changed: "true"

environment:
  matrix:
	- CMAKE_ARGS: -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 14 2015 64"
	PREFIX: c:\project_msvc

	- CMAKE_ARGS: -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 14 2015"
	PREFIX: c:\project_msvc

  before_build:
	- cmd: >-
	if exists %PREFIX% set NEEDSDEPENDS=rem
	%NEEDSDEPENDS% mkdir %PREFIX%\include\SDL2
	%NEEDSDEPENDS% mkdir %PREFIX%\lib
	%NEEDSDEPENDS% cd %TEMP%

	- cmd: >- 
	%NEEDSDEPENDS% appveyor DownloadFile http://www.libsdl.org/release/SDL2-devel-2.0.8-VC.zip
	%NEEDSDEPENDS% 7z x SDL2-devel-2.0.8-VC.zip > nul
    %NEEDSDEPENDS% copy SDL2-2.0.8\include\* %PREFIX%\include > nul
    %NEEDSDEPENDS% copy SDL2-2.0.8\lib\x64\* %PREFIX%\lib > nul

	- cmd: >- 
	%NEEDSDEPENDS% appveyor DownloadFile http://www.libsdl.org/release/SDL2_ttf-devel-2.0.8-VC.zip
	%NEEDSDEPENDS% 7z x SDL2_ttf-devel-2.0.8-VC.zip > nul
    %NEEDSDEPENDS% copy SDL2_ttf-2.0.8\include\* %PREFIX%\include > nul
    %NEEDSDEPENDS% copy SDL2_ttf-2.0.8\lib\x64\* %PREFIX%\lib > nul

	- cmd: >- 
	%NEEDSDEPENDS% appveyor DownloadFile http://www.libsdl.org/release/SDL2_image-devel-2.0.8-VC.zip
	%NEEDSDEPENDS% 7z x SDL2_image-devel-2.0.8-VC.zip > nul
    %NEEDSDEPENDS% copy SDL2_image-2.0.8\include\* %PREFIX%\include > nul
    %NEEDSDEPENDS% copy SDL2_image-2.0.8\lib\x64\* %PREFIX%\lib > nul

	- cmd: >- 
	%NEEDSDEPENDS% appveyor DownloadFile http://www.libsdl.org/release/SDL2_net-devel-2.0.8-VC.zip
	%NEEDSDEPENDS% 7z x SDL2_net-devel-2.0.8-VC.zip > nul
    %NEEDSDEPENDS% copy SDL2_net-2.0.8\include\* %PREFIX%\include > nul
    %NEEDSDEPENDS% copy SDL2_net-2.0.8\lib\x64\* %PREFIX%\lib > nul

	- cmd: >- 
	%NEEDSDEPENDS% appveyor DownloadFile http://www.libsdl.org/release/SDL2_mixer_net-devel-2.0.8-VC.zip
	%NEEDSDEPENDS% 7z x SDL2_mixer_net-devel-2.0.8-VC.zip > nul
    %NEEDSDEPENDS% copy SDL2_mixer_net-2.0.8\include\* %PREFIX%\include > nul
    %NEEDSDEPENDS% copy SDL2_mixer_net-2.0.8\lib\x64\* %PREFIX%\lib > nul


build_script:
- cmd: >-
  mkdir build
  
  cd build
  
  cmake c:\projects\source -G "Visual Studio 15"
  
  cmake --build . --config "Release"
test_script:
- cmd: ctest -C Debug

environment:
  variable1: value

image:
  - Visual Studio 2017
clone_folder: c:\projects\source

