version: "{branch}.{build}"

branches:
  only:
    - master
	- release

configuration: "Release"

platform: "x64"

shallow_copy: "true"
clone_depth: "1"

notifications:
  - provider: "Webhooks"
    url: "gitter appveyor integration link"
	on_build_success: "true"
	on_build_failure: "true"
	on_build_status_changed: "true"

environment:
  matrix:
	- APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
	  CMAKE_ARGS: -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 15 2017"
	  PREFIX: c:\project_msvc

	- APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
	  CMAKE_ARGS: -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 14 2015"
	  PREFIX: c:\project_msvc

	- APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2013"
	  CMAKE_ARGS: -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 12 2013"
	  PREFIX: c:\project_msvc

	- APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2012"
	  CMAKE_ARGS: -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 11 2012"
	  PREFIX: c:\project_msvc

	- APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2010"
	  CMAKE_ARGS: -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 10 2010"
	  PREFIX: c:\project_msvc

	- APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2008"
	  CMAKE_ARGS: -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 9 2008"
	  PREFIX: c:\project_msvc

  before_build:
	- cmd: >-
	if exists %PREFIX% set NEEDSDEPENDS=rem
	%NEEDSDEPENDS% mkdir %PREFIX%\include\SDL2
	%NEEDSDEPENDS% mkdir %PREFIX%\lib
	%NEEDSDEPENDS% cd %TEMP%

	- cmd: >- 
	%NEEDSDEPENDS% appveyor DownloadFile http://www.libsdl.org/release/SDL2-devel-2.0.8-VC.zip
	%NEEDSDEPENDS% 7z x SDL2-devel-2.0.8-VC.zip > nul
    %NEEDSDEPENDS% copy SDL2-2.0.8\include\* %PREFIX%\include > nul
    %NEEDSDEPENDS% copy SDL2-2.0.8\lib\x64\* %PREFIX%\lib > nul

	- cmd: >- 
	%NEEDSDEPENDS% appveyor DownloadFile http://www.libsdl.org/release/SDL2_ttf-devel-2.0.8-VC.zip
	%NEEDSDEPENDS% 7z x SDL2_ttf-devel-2.0.8-VC.zip > nul
    %NEEDSDEPENDS% copy SDL2_ttf-2.0.8\include\* %PREFIX%\include > nul
    %NEEDSDEPENDS% copy SDL2_ttf-2.0.8\lib\x64\* %PREFIX%\lib > nul

	- cmd: >- 
	%NEEDSDEPENDS% appveyor DownloadFile http://www.libsdl.org/release/SDL2_image-devel-2.0.8-VC.zip
	%NEEDSDEPENDS% 7z x SDL2_image-devel-2.0.8-VC.zip > nul
    %NEEDSDEPENDS% copy SDL2_image-2.0.8\include\* %PREFIX%\include > nul
    %NEEDSDEPENDS% copy SDL2_image-2.0.8\lib\x64\* %PREFIX%\lib > nul

	- cmd: >- 
	%NEEDSDEPENDS% appveyor DownloadFile http://www.libsdl.org/release/SDL2_net-devel-2.0.8-VC.zip
	%NEEDSDEPENDS% 7z x SDL2_net-devel-2.0.8-VC.zip > nul
    %NEEDSDEPENDS% copy SDL2_net-2.0.8\include\* %PREFIX%\include > nul
    %NEEDSDEPENDS% copy SDL2_net-2.0.8\lib\x64\* %PREFIX%\lib > nul

	- cmd: >- 
	%NEEDSDEPENDS% appveyor DownloadFile http://www.libsdl.org/release/SDL2_mixer_net-devel-2.0.8-VC.zip
	%NEEDSDEPENDS% 7z x SDL2_mixer_net-devel-2.0.8-VC.zip > nul
    %NEEDSDEPENDS% copy SDL2_mixer_net-2.0.8\include\* %PREFIX%\include > nul
    %NEEDSDEPENDS% copy SDL2_mixer_net-2.0.8\lib\x64\* %PREFIX%\lib > nul


build_script:
- cmd: >-
  cd %APPVEYOR_BUILD_FOLDER%
  cmkae
  mkdir build
  
  cd build
  
  cmake c:\projects\source -G "Visual Studio 15"
  
  cmake --build . --config "Release"

build_script:
  # build
  - |-
    %MINGW32% set PATH=c:\mingw\bin;%PATH%
    cd %APPVEYOR_BUILD_FOLDER%
    cmake -DCMAKE_PREFIX_PATH=%PREFIX% %CMAKE_ARGS% .
    cmake --build .
    %MINGW32% type FindSDL2PP.cmake
    %MINGW32% type sdl2pp.pc
  # tests; PATH here lists library search paths
  - |-
    set PATH=%PREFIX%\lib;%PATH%
    %MSVC% set PATH=%APPVEYOR_BUILD_FOLDER%\Debug;%PATH%
    %MINGW32% set PATH=%APPVEYOR_BUILD_FOLDER%;%PATH%
    ctest -V
test_script:
- cmd: ctest -C Debug

environment:
  variable1: value

image:
  - Visual Studio 2017
clone_folder: c:\projects\source

