#! /usr/bin/env sh

## Project information
printf -v project_name "%s" $(basename $(cat ~/.working-on))
read -r github_user_name < ~/.working-with

## Git init
git init .

## Folder setup
mkdir {src,include,lib,tests,docs,bin,m4,scripts}
mkdir docs/code
mkdir lib/argtable3
mkdir include/{utils,core}
mkdir include/utils/{misc,data-structures,algorithms}
mkdir src/{utils,core} 
mkdir src/utils/{misc,data-structures,algorithms}

## File setup
### C files
#### Core
m4 -P ~/.p-init/c/files/src/project.c.m4 > "src/${project_name}".c # base: ✓ (change header comment to project-args.c)

m4 -P ~/.p-init/c/files/include/utils/misc/common.h.m4 > include/utils/misc/common.h # base: ✓ (gnu extensions and cleanup macro)

m4 -P ~/.p-init/c/files/include/utils/misc/status-codes.h.m4 > include/utils/misc/status-codes.h # base: ✓
m4 -P ~/.p-init/c/files/src/utils/misc/status-codes.c.m4 > src/utils/misc/status-codes.c # ✓

m4 -P ~/.p-init/c/files/include/utils/misc/logger.h.m4 > include/utils/misc/logger.h # ✓
m4 -P ~/.p-init/c/files/src/utils/misc/logger.c.m4 > src/utils/misc/logger.c # ✓

m4 -P ~/.p-init/c/files/include/utils/misc/args.h.m4 > include/utils/misc/args.h # ✓
m4 -P ~/.p-init/c/files/src/utils/misc/args.c.m4 > src/utils/misc/args.c

## vimscript check suite template (refer to tests/test-project.c)
###
cp ~/.p-init/c/files/scripts/Rlinter scripts/.

#### Drop in libraries
wget https://raw.githubusercontent.com/argtable/argtable3/master/argtable3.h > lib/argtable3/argtable3.h
wget https://raw.githubusercontent.com/argtable/argtable3/master/argtable3.c > lib/argtable3/argtable3.c
### Autotools
wget http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_check_compile_flag.m4 > m4/ax_check_compile_flag.m4
wget http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_append_flag.m4 > m4/ax_append_flag.m4
m4 -P ~/.p-init/c/files/configure.ac.m4 > configure.ac # Define a PROJECT_BINARY macro based on host os
m4 -P ~/.p-init/c/files/Makefile.am.m4 > Makefile.am
### Sphinx
pushd docs/
sphinx-quickstart
popd

m4 -P ~/.p-init/c/files/docs/index.rst.m4 > docs/src/index.rst
m4 -P ~/.p-init/c/files/docs/design.rst.m4 > docs/src/design.rst
m4 -P ~/.p-init/c/files/docs/tutorial.rst.m4 > docs/src/tutorial.rst
m4 -P ~/.p-init/c/files/docs/guide.rst.m4 > docs/src/guide.rst
m4 -P ~/.p-init/c/files/docs/api.rst.m4 > docs/src/api.rst

### Travis CI
cp ~/.p-init/c/travis_ci/.travis.yml . 

### General
m4 -P ~/.p-init/c/git/LICENSE.md.m4 > LICENSE.md
cp ~/.p-init/c/git/LICENSE-docs.md > LICENSE-docs.md
m4 -P ~/.p-init/c/git/README.md.m4 > README.md # investigate git pages
m4 -P ~/.p-init/c/git/AUTHORS.md.m4 > AUTHORS.md # investigate practical usage of gpg keys
m4 -P ~/.p-init/c/git/CONTRIBUTING.md.m4 > CONTRIBUTING.md

### Git ignore
cp ~/.p-init/c/git/.gitignore . 
