// typedef SDL_Colour colour_asset;

SDL_Color tetromino[7][16] = {0};

GAME_STATUS game_assets__load_tetromino(game_asset* tetromino)
{
	game_asset left_tetromino[16] = {
		RED, 		
	}
	BUF_PUSH(tetromino, left_tetromino);
}

void game_assets__free(GAME_AssetManager* asset_manager)
{
		free(asset_manager);	
}

tetromino[0] = {
	BG_COLOUR, BG_COLOUR, RED, BG_COLOUR,
	BG_COLOUR, BG_COLOUR, RED, BG_COLOUR,
	BG_COLOUR, BG_COLOUR, RED, BG_COLOUR,
	BG_COLOUR, BG_COLOUR, RED, BG_COLOUR
};

tetromino[1] = {
	BG_COLOUR, BG_COLOUR, RED, BG_COLOUR,
	BG_COLOUR, RED, RED, BG_COLOUR,
	BG_COLOUR, RED, BG_COLOUR, BG_COLOUR,
	BG_COLOUR, BG_COLOUR, BG_COLOUR, BG_COLOUR
};

tetromino[2] = {
	BG_COLOUR, RED, BG_COLOUR, BG_COLOUR,
	BG_COLOUR, RED, RED, BG_COLOUR,
	BG_COLOUR, BG_COLOUR, RED, BG_COLOUR,
	BG_COLOUR, BG_COLOUR, BG_COLOUR, BG_COLOUR
};

tetromino[3] = {
	BG_COLOUR, BG_COLOUR, RED, BG_COLOUR,
	BG_COLOUR, RED, RED, BG_COLOUR,
	BG_COLOUR, RED, RED, BG_COLOUR,
	BG_COLOUR, BG_COLOUR, BG_COLOUR, BG_COLOUR
};

tetromino[4] = {
	BG_COLOUR, BG_COLOUR, RED, BG_COLOUR,
	BG_COLOUR, RED, RED, BG_COLOUR,
	BG_COLOUR, BG_COLOUR, RED, BG_COLOUR,
	BG_COLOUR, BG_COLOUR, BG_COLOUR, BG_COLOUR
};

tetromino[5] = {
	BG_COLOUR, BG_COLOUR, BG_COLOUR, BG_COLOUR,
	BG_COLOUR, RED, RED, BG_COLOUR,
	BG_COLOUR, BG_COLOUR, RED, BG_COLOUR,
	BG_COLOUR, BG_COLOUR, RED, BG_COLOUR
};

tetromino[6] = {
	BG_COLOUR, BG_COLOUR, BG_COLOUR, BG_COLOUR,
	BG_COLOUR, RED, RED, BG_COLOUR,
	BG_COLOUR, RED, BG_COLOUR, BG_COLOUR,
	BG_COLOUR, RED, BG_COLOUR, BG_COLOUR
};

