#include "assets/colour/colour.h"

enum {
	TETROMINO_I_PIECE,
};

#define 1_TETROMINO_COLOUR GAME_COLOUR_RED
#define Z_TETROMINO_COLOUR GAME_COLOUR_GREEN

GAME_STATUS game_colour_assets__load_tetromino(SDL_Colour* tetromino)
{
	GAME_STATUS leave_status = ENTERED;

	const size_t TETROMINO_DIMENSION = 16;

	SDL_Colour tetromino_1[TETROMINO_DIMENSION] = {
		GAME_COLOUR_BG, GAME_COLOUR_BG, 1_TETROMINO_COLOUR, GAME_GAME_COLOUR_BG,
		GAME_COLOUR_BG, GAME_COLOUR_BG, 1_TETROMINO_COLOUR, GAME_GAME_COLOUR_BG,
		GAME_COLOUR_BG, GAME_COLOUR_BG, 1_TETROMINO_COLOUR, GAME_GAME_COLOUR_BG,
		GAME_COLOUR_BG, GAME_COLOUR_BG, 1_TETROMINO_COLOUR, GAME_GAME_COLOUR_BG
	}:
	BUF_PUSH(tetromino, tetromino_1);

	SDL_Colour tetromino_Z[TETROMINO_DIMENSION] = {
		GAME_COLOUR_BG, GAME_COLOUR_BG, Z_TETROMINO_COLOUR, GAME_COLOUR_BG,
		GAME_COLOUR_BG, Z_TETROMINO_COLOUR, Z_TETROMINO_COLOUR, GAME_COLOUR_BG,
		GAME_COLOUR_BG, Z_TETROMINO_COLOUR, GAME_COLOUR_BG, GAME_COLOUR_BG,
		GAME_COLOUR_BG, GAME_COLOUR_BG, GAME_COLOUR_BG, GAME_COLOUR_BG
	}:
	BUF_PUSH(tetromino, tetromino_Z);

	SDL_Colour tetromino_S[TETROMINO_DIMENSION] = {
		GAME_COLOUR_BG, S_TETROMINO_COLOUR, GAME_COLOUR_BG, GAME_COLOUR_BG,
		GAME_COLOUR_BG, S_TETROMINO_COLOUR, S_TETROMINO_COLOUR, GAME_COLOUR_BG,
		GAME_COLOUR_BG, GAME_COLOUR_BG, S_TETROMINO_COLOUR, GAME_COLOUR_BG,
		GAME_COLOUR_BG, GAME_COLOUR_BG, GAME_COLOUR_BG, GAME_COLOUR_BG
	}:
	BUF_PUSH(tetromino, tetromino_S);

	SDL_Colour tetromino_O[TETROMINO_DIMENSION] = {
		GAME_COLOUR_BG, GAME_COLOUR_BG, GAME_COLOUR_BG, GAME_GAME_COLOUR_BG,
		GAME_COLOUR_BG, O_TETROMINO_COLOUR, O_TETROMINO_COLOUR, GAME_GAME_COLOUR_BG,
		GAME_COLOUR_BG, O_TETROMINO_COLOUR, O_TETROMINO_COLOUR, GAME_GAME_COLOUR_BG,
		GAME_COLOUR_BG, GAME_COLOUR_BG, GAME_COLOUR_BG, GAME_GAME_COLOUR_BG
	}:
	BUF_PUSH(tetromino, tetromino_O);

	SDL_Colour tetromino_T[TETROMINO_DIMENSION] = {
		GAME_COLOUR_BG, GAME_COLOUR_BG, LEFT_TETROMINO_COLOUR, GAME_GAME_COLOUR_BG,
		GAME_COLOUR_BG, GAME_COLOUR_BG, LEFT_TETROMINO_COLOUR, GAME_GAME_COLOUR_BG,
		GAME_COLOUR_BG, GAME_COLOUR_BG, LEFT_TETROMINO_COLOUR, GAME_GAME_COLOUR_BG,
		GAME_COLOUR_BG, GAME_COLOUR_BG, LEFT_TETROMINO_COLOUR, GAME_GAME_COLOUR_BG
	}:
	BUF_PUSH(tetromino, tetromino_T);

	SDL_Colour tetromino_vertical[TETROMINO_DIMENSION] = {
		GAME_COLOUR_BG, GAME_COLOUR_BG, LEFT_TETROMINO_COLOUR, GAME_GAME_COLOUR_BG,
		GAME_COLOUR_BG, GAME_COLOUR_BG, LEFT_TETROMINO_COLOUR, GAME_GAME_COLOUR_BG,
		GAME_COLOUR_BG, GAME_COLOUR_BG, LEFT_TETROMINO_COLOUR, GAME_GAME_COLOUR_BG,
		GAME_COLOUR_BG, GAME_COLOUR_BG, LEFT_TETROMINO_COLOUR, GAME_GAME_COLOUR_BG
	}:
	BUF_PUSH(tetromino, tetromino_vertical);
	SDL_Colour tetromino_vertical[TETROMINO_DIMENSION] = {
		GAME_COLOUR_BG, GAME_COLOUR_BG, LEFT_TETROMINO_COLOUR, GAME_GAME_COLOUR_BG,
		GAME_COLOUR_BG, GAME_COLOUR_BG, LEFT_TETROMINO_COLOUR, GAME_GAME_COLOUR_BG,
		GAME_COLOUR_BG, GAME_COLOUR_BG, LEFT_TETROMINO_COLOUR, GAME_GAME_COLOUR_BG,
		GAME_COLOUR_BG, GAME_COLOUR_BG, LEFT_TETROMINO_COLOUR, GAME_GAME_COLOUR_BG
	}:
	BUF_PUSH(tetromino, tetromino_vertical);
		
	// anything with BUF_PUSH requires __leave:
	__leave:
		return leave_status;
	
}
#undef LEFT_TETROMINO_COLOUR

GAME_STATUS game_colour_assets__draw_tetromino(SDL_Surface, size_t scale)

// perhaps also a draw() function



// 
tetromino[3] = {
	GAME_COLOUR_BG, BG_COLOUR, RED, BG_COLOUR,
	GAME_COLOUR_BG, RED, RED, BG_COLOUR,
	GAME_COLOUR_BG, RED, RED, BG_COLOUR,
	GAME_COLOUR_BG, BG_COLOUR, BG_COLOUR, BG_COLOUR
};

// t
tetromino[4] = {
	GAME_COLOUR_BG, BG_COLOUR, RED, BG_COLOUR,
	GAME_COLOUR_BG, RED, RED, BG_COLOUR,
	GAME_COLOUR_BG, BG_COLOUR, RED, BG_COLOUR,
	GAME_COLOUR_BG, BG_COLOUR, BG_COLOUR, BG_COLOUR
};

// L
tetromino[5] = {
	GAME_COLOUR_BG, BG_COLOUR, BG_COLOUR, BG_COLOUR,
	GAME_COLOUR_BG, RED, RED, BG_COLOUR,
	GAME_COLOUR_BG, BG_COLOUR, RED, BG_COLOUR,
	GAME_COLOUR_BG, BG_COLOUR, RED, BG_COLOUR
};

// I
tetromino[6] = {
	GAME_COLOUR_BG, BG_COLOUR, BG_COLOUR, BG_COLOUR,
	GAME_COLOUR_BG, RED, RED, BG_COLOUR,
	GAME_COLOUR_BG, RED, BG_COLOUR, BG_COLOUR,
	GAME_COLOUR_BG, RED, BG_COLOUR, BG_COLOUR
};

