#include "assets/colour/colour.h"

enum {
	TETROMINO_LEFT_PIECE,
	TETROMINO_RIGHT_PIECE,
};

enum {
	TETROMINO_TOP_LEFT,
}

#define LEFT_TETROMINO_COLOUR GAME_COLOUR_RED

colour_asset* tetrominoes = NULL;
if (colours_assets__load_tetrominoes(tetrominoes)) {
	tetrominoes[TETROMINO_LEFT][TOP_LEFT];
}

GAME_STATUS game_colour_assets__load_tetromino(SDL_Colour* tetromino)
{
	GAME_STATUS leave_status = ENTERED;

	const size_t TETROMINO_DIMENSION = 16;

	SDL_Colour left_tetromino[TETROMINO_DIMENSION] = {
		GAME_COLOUR_ASSET__LEFT_TETROMINO_COLOUR, GAME__BACKGROUND_COLOUR 
	}
	BUF_PUSH(tetromino, left_tetromino);


	// anything with BUF_PUSH requires __leave:
	__leave:
	
}

GAME_STATUS game_colour_assets__draw_tetromino(SDL_Surface, size_t scale)

// perhaps also a draw() function

tetromino[0] = {
	BG_COLOUR, BG_COLOUR, RED, BG_COLOUR,
	BG_COLOUR, BG_COLOUR, RED, BG_COLOUR,
	BG_COLOUR, BG_COLOUR, RED, BG_COLOUR,
	BG_COLOUR, BG_COLOUR, RED, BG_COLOUR
};

tetromino[1] = {
	BG_COLOUR, BG_COLOUR, RED, BG_COLOUR,
	BG_COLOUR, RED, RED, BG_COLOUR,
	BG_COLOUR, RED, BG_COLOUR, BG_COLOUR,
	BG_COLOUR, BG_COLOUR, BG_COLOUR, BG_COLOUR
};

tetromino[2] = {
	BG_COLOUR, RED, BG_COLOUR, BG_COLOUR,
	BG_COLOUR, RED, RED, BG_COLOUR,
	BG_COLOUR, BG_COLOUR, RED, BG_COLOUR,
	BG_COLOUR, BG_COLOUR, BG_COLOUR, BG_COLOUR
};

tetromino[3] = {
	BG_COLOUR, BG_COLOUR, RED, BG_COLOUR,
	BG_COLOUR, RED, RED, BG_COLOUR,
	BG_COLOUR, RED, RED, BG_COLOUR,
	BG_COLOUR, BG_COLOUR, BG_COLOUR, BG_COLOUR
};

tetromino[4] = {
	BG_COLOUR, BG_COLOUR, RED, BG_COLOUR,
	BG_COLOUR, RED, RED, BG_COLOUR,
	BG_COLOUR, BG_COLOUR, RED, BG_COLOUR,
	BG_COLOUR, BG_COLOUR, BG_COLOUR, BG_COLOUR
};

tetromino[5] = {
	BG_COLOUR, BG_COLOUR, BG_COLOUR, BG_COLOUR,
	BG_COLOUR, RED, RED, BG_COLOUR,
	BG_COLOUR, BG_COLOUR, RED, BG_COLOUR,
	BG_COLOUR, BG_COLOUR, RED, BG_COLOUR
};

tetromino[6] = {
	BG_COLOUR, BG_COLOUR, BG_COLOUR, BG_COLOUR,
	BG_COLOUR, RED, RED, BG_COLOUR,
	BG_COLOUR, RED, BG_COLOUR, BG_COLOUR,
	BG_COLOUR, RED, BG_COLOUR, BG_COLOUR
};

